# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ObjectDetection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectDetection
#  pod 'TensorFlowLiteSwift', "~> 2.4.0" # tensorflowlite cpu
  pod 'TensorFlowLiteSwift/Metal', '~> 0.0.1-nightly' # tensorflowlite gpu

end
